baseURL = "https://blog.muhammadilham.xyz"
languageCode = "en-us"
title = "Afterthought"
theme = "anubis"
paginate = 5

disqusShortname = "blog-bf7cs53gjc"
googleAnalytics = ""

[author]
name = "Muhammad Ilham"

[params]
author = "Muhammad Ilham"
description = "My personal blog. Mostly about tech."
dateFormat = "Mon, 02 Jan 2006"
paginationSinglePost = true
style = "auto"
readMore = true
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = false

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

[[params.social]]
id = "github"
url = "https://github.com/mhdiiilham/afterthought"

[[params.social]]
id = "linkedin"
url = "http://linkedin.com/in/muhammad-ilham-491a99194"

[[params.social]]
id = "twitter"
url = "http://twitter.com/w8roO"

[menu]

[[menu.main]]
identifier = "Blog"
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
identifier = "home"
name = "Home"
url = "https://muhammadilham.xyz"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3


[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
