[build]
publish = "public"
command = "hugo server"

[context.production.environment]
HUGO_VERSION = "0.104.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo server --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.104.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo server --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.104.3"

[context.branch-deploy]
command = "hugo server -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.104.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200
